-- Schema: catalogs, per-section tables, checks and indexes.

create type participant_status as enum ('in_progress', 'completed', 'excluded');
create type scale_instrument   as enum ('MAAS', 'PPS');

-- Catalogs (read-only for participants; seeded in seed.sql).
create table knowledge_area (
  id_area int generated by default as identity primary key,
  name    text not null unique
);

create table major (
  id_major int generated by default as identity primary key,
  fk_area  int not null references knowledge_area (id_area),
  name     text not null,
  unique (fk_area, name)
);

create table university_center (
  id_center int generated by default as identity primary key,
  name      text not null unique
);

create table study_modality (
  id_modality int generated by default as identity primary key,
  name        text not null unique
);

create table content_format (
  id_format int generated by default as identity primary key,
  name      text not null unique
);

create table device (
  id_device int generated by default as identity primary key,
  name      text not null unique
);

create table physical_activity (
  id_activity int generated by default as identity primary key,
  name        text not null unique
);

-- participant: root. id = auth.uid() from the anonymous sign-in. Created at
-- consent with status 'in_progress'; only status is ever updated.
create table participant (
  id_participant   uuid primary key default auth.uid(),
  created_at       timestamptz not null default now(),
  consent_accepted boolean not null check (consent_accepted = true),
  status           participant_status not null default 'in_progress',
  screen_width       int,
  screen_height      int,
  browser            text,
  origin             text check (origin is null or char_length(origin) <= 64),
  -- soft duplicate signal, not an identity (identical devices collide).
  device_fingerprint text check (device_fingerprint is null or char_length(device_fingerprint) <= 128)
);

create table meta_data (
  fk_participant uuid primary key references participant (id_participant) on delete cascade,
  welcome_emoji  text check (welcome_emoji is null or char_length(welcome_emoji) <= 8),
  emoji_answer   text check (emoji_answer  is null or char_length(emoji_answer)  <= 8),
  wants_results  boolean not null default false,
  email          text check (email is null or char_length(email) <= 254)
);

create table cpt_session (
  fk_participant     uuid primary key references participant (id_participant) on delete cascade,
  parameters         jsonb not null,
  started_at         timestamptz not null,
  finished_at        timestamptz not null,
  focus_losses       smallint not null check (focus_losses >= 0),
  fullscreen_exits   smallint not null check (fullscreen_exits >= 0),
  practice_attempts  smallint not null check (practice_attempts between 1 and 2),
  practice_hits_pct  numeric  not null check (practice_hits_pct between 0 and 100),
  check (finished_at > started_at)
);

create table cpt_trial (
  fk_participant  uuid not null references cpt_session (fk_participant) on delete cascade,
  n_trial         int  not null,
  block           smallint not null,
  is_practice     boolean  not null,
  letter          char(1)  not null check (letter ~ '^[A-Z]$'),
  planned_onset_ms double precision not null,
  actual_onset_ms  double precision not null,
  rt_ms            double precision check (rt_ms is null or rt_ms >= 0),
  primary key (fk_participant, n_trial)
);

create table personal_habits (
  fk_participant     uuid primary key references participant (id_participant) on delete cascade,
  fk_main_device     int not null references device (id_device),
  fk_physical_activity int not null references physical_activity (id_activity),
  hours_short_videos numeric(4,2) not null check (hours_short_videos between 0 and 24),
  hours_long_videos  numeric(4,2) not null check (hours_long_videos  between 0 and 24),
  hours_audio_podcast numeric(4,2) not null check (hours_audio_podcast between 0 and 24),
  hours_reading      numeric(4,2) not null check (hours_reading      between 0 and 24),
  hours_study_daily  numeric      not null check (hours_study_daily  between 0 and 24),
  hours_sleep_avg    numeric      not null check (hours_sleep_avg    between 0 and 24),
  constant_scroll    smallint     not null check (constant_scroll    between 0 and 4),
  academic_multitask smallint     not null check (academic_multitask between 0 and 4),
  uses_ai            text check (uses_ai is null or uses_ai in ('si', 'no')),
  ai_relationship    text check (ai_relationship is null or ai_relationship in ('yo', 'ia', 'ambas', 'nose')),
  ai_purposes        text[],
  ai_tools           text[],
  ai_liking          text check (ai_liking is null or ai_liking in ('si', 'no', 'maso', 'nose'))
);

create table content_preference (
  fk_participant uuid not null references participant (id_participant) on delete cascade,
  fk_format      int  not null references content_format (id_format),
  primary key (fk_participant, fk_format)
);

-- Long format (one row per item), required for Cronbach's alpha.
create table scale_response (
  fk_participant uuid not null references participant (id_participant) on delete cascade,
  instrument     scale_instrument not null,
  n_item         smallint not null,
  value          smallint not null,
  primary key (fk_participant, instrument, n_item),
  check (
    (instrument = 'MAAS' and n_item between 1 and 15 and value between 1 and 6) or
    (instrument = 'PPS'  and n_item between 1 and 12 and value between 1 and 5)
  )
);

create table academic_data (
  fk_participant         uuid primary key references participant (id_participant) on delete cascade,
  age                    smallint not null check (age > 0 and age <= 120),
  sex                    text not null check (sex in ('Femenino', 'Masculino')),
  fk_center              int not null references university_center (id_center),
  fk_major               int not null references major (id_major),
  fk_modality            int not null references study_modality (id_modality),
  academic_year          smallint not null check (academic_year between 1 and 5),
  general_average        numeric  not null check (general_average between 0 and 100),
  failed_classes_semester smallint not null check (failed_classes_semester between 0 and 3)
);
