-- AI catalogs: move ai_purposes / ai_tools off personal_habits into catalog +
-- bridge tables, mirroring content_format / content_preference. The fixed AI
-- enums (uses_ai, ai_relationship, ai_liking) stay inline.
-- ⚠️ Drops the old array columns; run before any real data is collected.

create table if not exists ai_purpose (
  id_purpose int generated by default as identity primary key,
  name       text not null unique
);

create table if not exists ai_tool (
  id_tool int generated by default as identity primary key,
  name    text not null unique
);

create table if not exists ai_purpose_pref (
  fk_participant uuid not null references participant (id_participant) on delete cascade,
  fk_purpose     int  not null references ai_purpose (id_purpose),
  primary key (fk_participant, fk_purpose)
);

create table if not exists ai_tool_use (
  fk_participant uuid not null references participant (id_participant) on delete cascade,
  fk_tool        int  not null references ai_tool (id_tool),
  primary key (fk_participant, fk_tool)
);

alter table personal_habits drop column if exists ai_purposes;
alter table personal_habits drop column if exists ai_tools;

alter table ai_purpose enable row level security;
create policy ai_purpose_select on ai_purpose for select to anon, authenticated using (true);

alter table ai_tool enable row level security;
create policy ai_tool_select on ai_tool for select to anon, authenticated using (true);

do $$
declare t text;
begin
  foreach t in array array['ai_purpose_pref','ai_tool_use'] loop
    execute format('alter table %I enable row level security', t);
    execute format(
      'create policy %I on %I for insert to authenticated
         with check (fk_participant = (select auth.uid()))', t || '_insert', t);
    execute format(
      'create policy %I on %I for select to authenticated
         using (fk_participant = (select auth.uid()))', t || '_select', t);
  end loop;
end $$;

-- Rebuild the view: ai_purposes / ai_tools now aggregate from the bridge tables.
drop view v_analysis_dataset;
create view v_analysis_dataset
with (security_invoker = true) as
select
  p.id_participant,
  p.created_at,

  dev.name as main_device,
  pa.name  as physical_activity,
  ph.hours_short_videos,
  ph.hours_long_videos,
  ph.hours_audio_podcast,
  ph.hours_reading,
  ph.hours_study_daily,
  ph.hours_sleep_avg,
  ph.constant_scroll,
  ph.academic_multitask,
  ph.uses_ai,
  ph.ai_relationship,
  (select array_agg(ap.name order by ap.name)
     from ai_purpose_pref app
     join ai_purpose ap on ap.id_purpose = app.fk_purpose
    where app.fk_participant = p.id_participant) as ai_purposes,
  (select array_agg(ait.name order by ait.name)
     from ai_tool_use atu
     join ai_tool ait on ait.id_tool = atu.fk_tool
    where atu.fk_participant = p.id_participant) as ai_tools,
  ph.ai_liking,
  md.welcome_emoji,
  md.emoji_answer,
  md.wants_results,
  (ph.hours_short_videos + ph.hours_long_videos + ph.hours_audio_podcast) as hours_multimedia,
  -- share of screen consumption that is audiovisual vs reading.
  -- DEFINITION TO CONFIRM with the team; adjust here if it changes.
  (ph.hours_short_videos + ph.hours_long_videos + ph.hours_audio_podcast)
    / nullif(ph.hours_short_videos + ph.hours_long_videos + ph.hours_audio_podcast + ph.hours_reading, 0)
    as multimedia_ratio,

  (select array_agg(cf.name order by cf.name)
     from content_preference cp
     join content_format cf on cf.id_format = cp.fk_format
    where cp.fk_participant = p.id_participant) as preferred_formats,

  (select sum(value)   from scale_response r where r.fk_participant = p.id_participant and r.instrument = 'MAAS') as maas_sum,
  (select avg(value)   from scale_response r where r.fk_participant = p.id_participant and r.instrument = 'MAAS') as maas_mean,
  (select count(*)     from scale_response r where r.fk_participant = p.id_participant and r.instrument = 'MAAS') as maas_n_items,
  (select sum(value)   from scale_response r where r.fk_participant = p.id_participant and r.instrument = 'PPS')  as pps_sum,
  (select avg(value)   from scale_response r where r.fk_participant = p.id_participant and r.instrument = 'PPS')  as pps_mean,
  (select count(*)     from scale_response r where r.fk_participant = p.id_participant and r.instrument = 'PPS')  as pps_n_items,

  ad.age,
  ad.sex,
  uc.name  as university_center,
  mj.name  as major,
  ka.name  as knowledge_area,
  sm.name  as study_modality,
  ad.academic_year,
  ad.general_average,
  ad.failed_classes_semester,

  cs.parameters as cpt_parameters,
  cs.started_at   as cpt_started_at,
  cs.finished_at  as cpt_finished_at,
  cs.focus_losses,
  cs.fullscreen_exits,
  cs.practice_attempts,
  cs.practice_hits_pct
from participant p
join personal_habits   ph  on ph.fk_participant  = p.id_participant
join academic_data     ad  on ad.fk_participant  = p.id_participant
join meta_data         md  on md.fk_participant  = p.id_participant
join cpt_session       cs  on cs.fk_participant  = p.id_participant
join device            dev on dev.id_device      = ph.fk_main_device
join physical_activity pa  on pa.id_activity     = ph.fk_physical_activity
join university_center  uc on uc.id_center       = ad.fk_center
join major             mj  on mj.id_major        = ad.fk_major
join knowledge_area    ka  on ka.id_area         = mj.fk_area
join study_modality    sm  on sm.id_modality     = ad.fk_modality
where p.status = 'completed';

revoke all on v_analysis_dataset from anon, authenticated;
